#define TOPMC_PERF_PMC_MASK 0LL
//#define TOPMC_PERF_PMC_MASK   0xffff800000000000
/* Intel Xeon E5 v2-based CPU performance counters */

/* incore msrs*/
#define MSR_CORE_PERF_FIXED_CTR0        0x00000309
#define MSR_CORE_PERF_FIXED_CTR1        0x0000030a
#define MSR_CORE_PERF_FIXED_CTR2        0x0000030b
#define MSR_CORE_PERF_FIXED_CTR_CTRL    0x0000038d
#define MSR_CORE_PERF_GLOBAL_STATUS     0x0000038e
#define MSR_CORE_PERF_GLOBAL_CTRL       0x0000038f
#define MSR_CORE_PERF_GLOBAL_OVF_CTRL   0x00000390

#define MSR_CORE_PERF_NUM_PMC 4
#define MSR_CORE_PERF_IDX_PMC 0
#define MSR_CORE_PERF_IDX_FIX 32
#define MSR_CORE_PERF_NUM_FIX 3

#define TOPMC_MSR_XEON55XX_PERFCTR0                     0x000000c1
#define TOPMC_MSR_XEON55XX_PERFCTR1                     0x000000c2
#define TOPMC_MSR_XEON55XX_PERFCTR2                     0x000000c3
#define TOPMC_MSR_XEON55XX_PERFCTR3                     0x000000c4
#define TOPMC_MSR_XEON55XX_EVNTSEL0                     0x00000186
#define TOPMC_MSR_XEON55XX_EVNTSEL1                     0x00000187
#define TOPMC_MSR_XEON55XX_EVNTSEL2                     0x00000188
#define TOPMC_MSR_XEON55XX_EVNTSEL3                     0x00000189

#define TOPMC_MSR_XEON55XX_PerfCtrNum   (TOPMC_MSR_XEON55XX_PERFCTR3-TOPMC_MSR_XEON55XX_PERFCTR0 +1)
#define TOPMC_MAX_NAMELEN       16

//#counter event format:'**--xyz#'
//#'**' stands for event
//#'--' stands for unit mask
//#'x' stands for cmask (only 4-bit value)
//#'y' stands for inv 
//#'z' stands for edge
//#'#' stands for usr/kernel:0-nothing,1-user,2-kernel,3-user and kernel

/*
#define TOPMC_EVENT_LENGTH      6
#define TOPMC_EVENT_MASK_KERNEL_USER    0xf
#define TOPMC_EVENT_MASK_UNIT                   0xff0
#define TOPMC_EVENT_MASK_LOW_EVENT              0xff000
#define TOPMC_EVENT_MASK_HIGH_EVENT             0xf00000
#define TOPMC_EVENT_BITS_KERNEL_USER    0
#define TOPMC_EVENT_BITS_UNIT                   4
#define TOPMC_EVENT_BITS_LOW_EVENT              12
#define TOPMC_EVENT_BITS_HIGH_EVENT             20
*/
#define TOPMC_EVENT_LENGTH      8
#define TOPMC_EVENT_MASK_LOW_EVENT      0xff000000
#define TOPMC_EVENT_MASK_UNIT           0xff0000
#define TOPMC_EVENT_MASK_CMASK          0xf000
#define TOPMC_EVENT_MASK_INV            0x100
#define TOPMC_EVENT_MASK_EDGE           0x10
#define TOPMC_EVENT_MASK_KERNEL_USER    0xf
//#define TOPMC_EVENT_MASK_HIGH_EVENT             0xf00000
#define TOPMC_EVENT_BITS_LOW_EVENT              24
#define TOPMC_EVENT_BITS_UNIT                   16
#define TOPMC_EVENT_BITS_CMASK              12
#define TOPMC_EVENT_BITS_INV                8
#define TOPMC_EVENT_BITS_EDGE               4
#define TOPMC_EVENT_BITS_KERNEL_USER    0
//#define TOPMC_EVENT_BITS_HIGH_EVENT             20

#define MSR_PPRO_EVENTSEL_RESERVED      ((0xFFFFFFFFULL<<32)|(1ULL<<21))

/*offcore msrs */
#define TOPMC_MSR_XEON55XX_OFFCORE_RSP0    0x1a6

/*uncore msrs*/
#if 0
#define TOPMC_MSR_XEON55XX_UNC_EVNTSEL0    0x3c0
#define TOPMC_MSR_XEON55XX_UNC_PERFCTR0    0x3b0
#define TOPMC_MSR_XEON55XX_UNC_FIXED_CTRL  0x395
#define TOPMC_MSR_XEON55XX_UNC_FIXED_CTR0  0x394
#define TOPMC_MSR_XEON55XX_UNC_ADDROP      0x396
#define TOPMC_MSR_XEON55XX_UNC_GLOBAL_CTRL 0x391
#define TOPMC_MSR_XEON55XX_UNC_GLOBAL_STAT 0x392
#define TOPMC_MSR_XEON55XX_UNC_GLOBAL_OVF_CTRL 0x393
#endif

#define TOPMC_U_MSR_PMON_GLOBAL_CONFIG 0x0C06
#define TOPMC_U_MSR_PMON_GLOBAL_STATUS 0x0C01
#define TOPMC_U_MSR_PMON_GLOBAL_CTL 0x0C00

/*UBox*/
#define TOPMC_U_MSR_PMON_CTR1 0x0C17
#define TOPMC_U_MSR_PMON_CTR0 0x0C16
#define TOPMC_U_MSR_PMON_BOX_STATUS 0x0C15
#define TOPMC_U_MSR_PMON_CTL1 0x0C11
#define TOPMC_U_MSR_PMON_CTL0 0x0C10
#define TOPMC_U_MSR_PMON_UCLK_FIXED_CTR 0x0C09
#define TOPMC_U_MSR_PMON_UCLK_FIXED_CTL 0x0C08

/*PCU*/
#define TOPMC_PCU_MSR_PMON_CTR3 0x0C39
#define TOPMC_PCU_MSR_PMON_CTR2 0x0C38
#define TOPMC_PCU_MSR_PMON_CTR1 0x0C37
#define TOPMC_PCU_MSR_PMON_CTR0 0x0C36
#define TOPMC_PCU_MSR_PMON_BOX_FILTER 0x0C34
#define TOPMC_PCU_MSR_PMON_CTL3 0x0C33
#define TOPMC_PCU_MSR_PMON_CTL2 0x0C32
#define TOPMC_PCU_MSR_PMON_CTL1 0x0C31
#define TOPMC_PCU_MSR_PMON_CTL0 0x0C30
#define TOPMC_PCU_MSR_PMON_BOX_STATUS 0x0C35
#define TOPMC_PCU_MSR_PMON_BOX_CTL 0x0C24 
#define TOPMC_PCU_MSR_CORE_C6_CTR 0x03FD
#define TOPMC_PCU_MSR_CORE_C3_CTR 0x03FC

/*CBox*/
#define TOPMC_C0_MSR_PMON_CTR3 0x0D19
#define TOPMC_C0_MSR_PMON_CTR2 0x0D18
#define TOPMC_C0_MSR_PMON_CTR1 0x0D17
#define TOPMC_C0_MSR_PMON_CTR0 0x0D16
#define TOPMC_C0_MSR_PMON_BOX_FILTER 0x0D14
#define TOPMC_C0_MSR_PMON_BOX_FILTER1 0x0D1A
#define TOPMC_C0_MSR_PMON_CTL3 0x0D13
#define TOPMC_C0_MSR_PMON_CTL2 0x0D12
#define TOPMC_C0_MSR_PMON_CTL1 0x0D11
#define TOPMC_C0_MSR_PMON_CTL0 0x0D10
#define TOPMC_C0_MSR_PMON_BOX_CTL 0x0D04

#define TOPMC_CBox_MSR_PMON_BOX_Distance 0x20 

#define TOPMC_MSR_IVYBRIGE_E_UNC_PerfCtrNum 10
#define TOPMC_U_MSR_PMON_PerfCtrNum 2
#define TOPMC_PCU_MSR_PMON_PerfCtrNum 4
#define TOPMC_CBox_MSR_PMON_PerfCtrNum 4

#define TOPMC_MSR_XEON55XX_UNC_IDX_FIXED 32
#define TOPMC_MSR_XEON55XX_UNC_BITS_MAX_PMC 7
#define TOPMC_MSR_XEON55XX_UNC_BITS_MIN_PMC 0
#define TOPMC_MSR_XEON55XX_UNC_IDX_PMC TOPMC_MSR_XEON55XX_UNC_BITS_MIN_PMC
#define TOPMC_MSR_XEON55XX_UNC_BITS_NUM_PMC (TOPMC_MSR_XEON55XX_UNC_BITS_MAX_PMC - TOPMC_MSR_XEON55XX_UNC_BITS_MIN_PMC + 1)

#define TOPMC_MSR_XEON55XX_UNC_EVENTSEL_RESERVED ((0xFFFFFFFFULL << 32) | (1ULL << 21) | (1ULL << 19) | (1ULL << 16))


#define TOPMC_CTRL_SET_ACTIVE(n) (n |= (1<<22))
#define TOPMC_CTRL_SET_INACTIVE(n) (n &= ~(1<<22))
#define TOPMC_CTRL_CLEAR_LO(x) (x &= (1<<21))
#define TOPMC_CTRL_CLEAR_HI(x) (x &= 0xfffffcf0)
#define TOPMC_CTRL_SET_ENABLE(val) (val |= 1<<20)
#define TOPMC_CTRL_SET_USR(val,u) (val |= ((u & 1) << 16))
#define TOPMC_CTRL_SET_KERN(val,k) (val |= ((k & 1) << 17))
#define TOPMC_CTRL_SET_UM(val, m) (val |= (m << 8))
#define TOPMC_CTRL_SET_EVENT_LOW(val, e) (val |= (e & 0xff))
#define TOPMC_CTRL_SET_CM(val, m) (val |= (m&0xff << 24))
#define TOPMC_CTRL_SET_INV(val, m) (val |= ((m&0x1) << 23))
#define TOPMC_CTRL_SET_EDGE(val, m) (val |= ((m&0x1) << 18))

